FROM python:3.11-slim

WORKDIR /app

# Fix Debian repo expiration
RUN sed -i 's/deb.debian.org/archive.debian.org/g' /etc/apt/sources.list && \
    sed -i 's/security.debian.org/archive.debian.org/g' /etc/apt/sources.list

COPY scheduler/crontab.txt /etc/crontab

RUN apt-get update && apt-get install -y cron && \
    pip install requests psycopg2-binary pandas python-dotenv && \
    crontab /etc/crontab

COPY . /app

CMD ["cron", "-f"]


 # FROM python:3.11-slim

 # WORKDIR /app

 # RUN apt-get update && apt-get install -y cron

 # COPY scheduler/crontab.txt /etc/crontab
 # RUN crontab /etc/crontab

 # CMD ["cron", "-f"]
